/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import static basiclibrary.Library.*;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testRollMethod() {
       Library classUnderTest=new Library();
       int[] actualResult=classUnderTest.roll(4);
        assertEquals(4,actualResult.length);
    }
    @Test public void testContainDuplicateMethod() {
        int[] testArr={1,2,2,5};
        boolean actualResult=containsDuplicates(testArr);
        assertTrue(actualResult);
    }
    @Test public void testAverageMethod() {

        int[] testArr={1,2,3,4,5};
        double expectedResult=3;
        double actualResult=calculateAverage(testArr);
        assertEquals(expectedResult,actualResult,0);
    }
    @Test public void testGetLowestAverageArrayMethod() {
        int[][] testArr={
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] actualResult=getBackLowAvgArray(testArr);
        int[] expectedResult={55, 54, 60, 53, 59, 57, 61};
        assertArrayEquals(expectedResult,actualResult);
    }


}
