/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
public static void main(String[] args){
    Restaurant restaurant=new Restaurant("amman");
    restaurant.setPriceCategory(2);
    System.out.println("price: "+restaurant.getPriceCategory());
    restaurant.addReview("yazan","not good restaurant",2);
    restaurant.addReview("rami","better restaurant ever",4);

    System.out.println(restaurant);

}
}
