/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
public static void main(String[] args){
    Restaurant restaurant=new Restaurant("amman");
    restaurant.setPriceCategory(2);
    System.out.println("price: "+restaurant.getPriceCategory());
    Review review=new Review("yazan","hot dog",4);
    System.out.println(review);
    restaurant.addReview(review);
    System.out.println("-----------------------------------------------------");
    Review review2=new Review("rami","better restaurant ever",1);
    System.out.println(review2);
    System.out.println("-----------------------------------------------------");
    restaurant.addReview(review2);
    System.out.println(restaurant);
    System.out.println("-----------------------------------------------------");
    Shop newShop=new Shop("nike","good shop");
    newShop.setPriceCategory(4);
    newShop.addReview(review);
    System.out.println(newShop);
    System.out.println("-----------------------------------------------------");
    Theater theater=new Theater("amman");
    theater.addMovie("titanic");
    Review newReview=new Review("nike","good theater",3);
    theater.addMovieReview(newReview,"titanic");
    Review newReview1=new Review("yazan","good theater",1);
    theater.addMovie("grid");
    theater.addMovieReview(newReview1,"grid");
    System.out.println(theater);
}
}
